server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: vault-client-service
  cloud:
    vault:
      authentication: TOKEN
      uri: http://localhost:8200
      token: ${spring.cloud.vault.token}  # Use token from secrets.yaml
      kv:
        enabled: true
        backend: secret       # KV backend name
        default-context: demo # Default context, adjust as needed
  config:
    import: vault://, secrets.yaml